### ISSUE TITLE
How to train this model on the other datasets?

### ISSUE THREAD

**Issue by weiningwei** [cvg/SOLD2#19] opened 2021-07-10 14:39 UTC
Hello, thank you for sharing the code!
If I want to train this model on the other datasets such as kitti dataset, could you provide some steps or suggestions? Thank you very much.

**Comment by rpautrat** [comment] 2021-07-13 10:42
Hi,
You could run the exact same steps as in the Readme, but replacing the Wireframe dataset with the dataset of your choice. This means that you would need to create a new dataloader (you can take inspiration from `dataset/wireframe_dataset.py`) that is adapted to your dataset (e.g. to the path and structure of your dataset), and adapt your own config file to this dataset. You would also need to update `dataset/dataset_util.py` to be able to load your new dataloader within the rest of the code. Once again, I encourage you to copy the code loading the wireframe dataset and to adapt it to your own dataset.

**Comment by Machine97** [comment] 2021-07-15 06:14
> Hi,
> You could run the exact same steps as in the Readme, but replacing the Wireframe dataset with the dataset of your choice. This means that you would need to create a new dataloader (you can take inspiration from `dataset/wireframe_dataset.py`) that is adapted to your dataset (e.g. to the path and structure of your dataset), and adapt your own config file to this dataset. You would also need to update `dataset/dataset_util.py` to be able to load your new dataloader within the rest of the code. Once again, I encourage you to copy the code loading the wireframe dataset and to adapt it to your own dataset.

Hi,
I want to train this model on our own data set. In addition to what you said, I also need to prepare ‘label.npz’ corresponding to each picture in the training set and test set like Wireframe dataset. Do you know how can I get these 'label.npz'?

**Comment by rpautrat** [comment] 2021-07-15 07:26
Hi,
Indeed, you would also need to generate the pseudo ground truth for your dataset. You can follow the steps 2 and 3 of the Readme for that, adapting the dataset config to your own dataset instead of the wireframe one.

**Comment by Machine97** [comment] 2021-07-15 07:54
> Hi,
> Indeed, you would also need to generate the pseudo ground truth for your dataset. You can follow the steps 2 and 3 of the Readme for that, adapting the dataset config to your own dataset instead of the wireframe one.

Thank you for your replying. I know what you said. However, in the step2, as shown in the figure, the image and label.npz file in Wireframe dataset will be taken as input. If I train on my own dataset, how can I get the label.npz file corresponding to my own dataset?
<img width="446" alt="截屏2021-07-15 下午3 52 57" src="https://user-images.githubusercontent.com/53359490/125750827-ecc8b503-293c-4098-b97e-34dad08fd370.png">

**Comment by rpautrat** [comment] 2021-07-15 08:03
You shouldn't need these labels, they are just the labels of the original Wireframe dataset left here in case you would like to compare with them. In theory SOLD² is self-supervised and doesn't require labels.

Commenting out the lines `gt_source_train` and `gt_source_test` in the dataset config file will make sure that the code will not try to load these labels.

**Comment by Machine97** [comment] 2021-07-15 08:10
> You shouldn't need these labels, they are just the labels of the original Wireframe dataset left here in case you would like to compare with them. In theory SOLD² is self-supervised and doesn't require labels.
> 
> Commenting out the lines `gt_source_train` and `gt_source_test` in the dataset config file will make sure that the code will not try to load these labels.

OK, I see. Thank you very much.

**Comment by Machine97** [comment] 2021-07-20 07:29
> You shouldn't need these labels, they are just the labels of the original Wireframe dataset left here in case you would like to compare with them. In theory SOLD² is self-supervised and doesn't require labels.
> 
> Commenting out the lines `gt_source_train` and `gt_source_test` in the dataset config file will make sure that the code will not try to load these labels.

Hi,
In the step2, I tried commenting out the lines gt_source_train and gt_source_test in the dataset config file as you said. However, the code  load the label.npz file. When I comment the lines gt_source_train and gt_source_test, then gt_source == 'official'. In this case, the program will executes the function 'train_preprocessing(data)'. In the function 'train_preprocessing(data)', its input 'data' includes the information in label.npz file.  I'm so confused about this.

**Comment by Machine97** [comment] 2021-07-20 07:31
> > You shouldn't need these labels, they are just the labels of the original Wireframe dataset left here in case you would like to compare with them. In theory SOLD² is self-supervised and doesn't require labels.
> > Commenting out the lines `gt_source_train` and `gt_source_test` in the dataset config file will make sure that the code will not try to load these labels.
> 
> Hi,
> In the step2, I tried commenting out the lines gt_source_train and gt_source_test in the dataset config file as you said. However, the code load the label.npz file. When I comment the lines gt_source_train and gt_source_test, then gt_source == 'official'. In this case, the program will executes the function 'train_preprocessing(data)'. In the function 'train_preprocessing(data)', its input 'data' includes the information in label.npz file. I'm so confused about this.
[
Duplicate of #
<img width="981" alt="截屏2021-07-20 下午3 22 10" src="https://user-images.githubusercontent.com/53359490/126280183-61d7ce88-dfaf-41ca-9fe1-bac4d2e956d1.png">
<img width="826" alt="截屏2021-07-20 下午3 22 47" src="https://user-images.githubusercontent.com/53359490/126280192-13bd6173-e92d-4f96-be2b-9503140b26b6.png">
](url)

**Comment by rpautrat** [comment] 2021-07-20 07:46
Ah I see, you are correct indeed. Sorry my mistake.

Instead of copying the code of the Wireframe dataset and adapt it to your own dataset, you should actually copy the code for Holicity: `dataset/holicity_dataset.py`. In this one there is no 'train_preprocessing', so it can only use 'export_preprocessing' to create the pseudo ground truth (gt_source_train and gt_source_test should be commented in the config file), and then 'train_preprocessing_exported' for training, once you have created the ground truth. This should solve your issue.

**Comment by Machine97** [comment] 2021-07-20 07:51
> Ah I see, you are correct indeed. Sorry my mistake.
> 
> Instead of copying the code of the Wireframe dataset and adapt it to your own dataset, you should actually copy the code for Holicity: `dataset/holicity_dataset.py`. In this one there is no 'train_preprocessing', so it can only use 'export_preprocessing' to create the pseudo ground truth (gt_source_train and gt_source_test should be commented in the config file), and then 'train_preprocessing_exported' for training, once you have created the ground truth. This should solve your issue.

Thank you very much for your quick reply. I'll try it as you said.

**Comment by huidemie** [comment] 2021-07-24 08:18
> Ah I see, you are correct indeed. Sorry my mistake.
> 
> Instead of copying the code of the Wireframe dataset and adapt it to your own dataset, you should actually copy the code for Holicity: `dataset/holicity_dataset.py`. In this one there is no 'train_preprocessing', so it can only use 'export_preprocessing' to create the pseudo ground truth (gt_source_train and gt_source_test should be commented in the config file), and then 'train_preprocessing_exported' for training, once you have created the ground truth. This should solve your issue.

I tryed what you said, trying to use holicity dataset proprecessing .But I can not generate "junctions" ,"heatmap" and "valid_mask" for data. It cause an error in train.py , line 253. Do you have any suggestion?

**Comment by rpautrat** [comment] 2021-07-24 19:25
Did you generate the pseudo ground truth for your dataset? Before the actual training, you need to run the steps 2 and 3 of the ReadMe (adapted to your own dataset of course).

**Comment by miaoqiz** [comment] 2021-08-18 03:01
Hi @rpautrat 

Thanks so much for the advise!

I have followed the steps and used "holicity_dataset.py" and "holicity_dataset.yaml" to run training on custom dataset.

Step#2 are good for both "training" dataset and "test" dataset.

When it comes to Step#3, there seems to be error when converting the results ( see below ).

---------------------------------------------------------------
**Training** dataset:

 74%|###############################           | 96/130 [03:07<01:06,  1.95s/it]
Traceback (most recent call last):
  File "convert_homography_results.py", line 119, in <module>
    junctions_pred_raw, heatmap_pred, device=device)
  File "../model/line_detection.py", line 123, in detect
    candidate_map)
  File "../model/line_detection.py", line 291, in candidate_suppression
    proj = (torch.einsum('bij,bjk->bik', cand_vecs, dir_vecs[..., None])
  File ".local/lib/python3.6/site-packages/torch/functional.py", line 201, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: shape '[1, 1, 2]' is invalid for input of size 0

---------------------------------
**Test** dataset

19%|########                                   | 15/80 [00:42<03:06,  2.87s/it]
Traceback (most recent call last):
  File "convert_homography_results.py", line 119, in <module>
    junctions_pred_raw, heatmap_pred, device=device)
  File "../model/line_detection.py", line 214, in detect
    junctions, line_map_pred, heatmap, H, W, device)
  File "../model/line_detection.py", line 389, in refine_junction_perturb
    refined_segments = torch.cat(refined_segment_lst, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]

---------------------------------------------------------------

It seems like some of the exported results in step#2 are empty. 

Can you kindly advise how to fix the errors?

Thanks so much and have a good day!

**Comment by rpautrat** [comment] 2021-08-18 12:02
Hi,

Indeed, it probably happened because no junctions were detected. I pushed a quick fix to that, could you please pull the latest version and try again?

This means that there will be some images in your dataset that will have no ground truth lines, so might want to remove these images to avoid subsequent problems.

**Comment by miaoqiz** [comment] 2021-08-18 20:39
Hi @rpautrat 

How are you?

Thanks so much for the quick fix! I appreciate it.

Now the training dataset has been converted successfully. 

The test dataset conversion still seems to have the issue:

-----------------------------------------------------------------------

 55%|#######################6                   | 44/80 [00:19<00:16,  2.23it/s]
Traceback (most recent call last):
  File "convert_homography_results.py", line 119, in <module>
    junctions_pred_raw, heatmap_pred, device=device)
  File "../model/line_detection.py", line 127, in detect
    candidate_map)
  File "../model/line_detection.py", line 295, in candidate_suppression
    proj = (torch.einsum('bij,bjk->bik', cand_vecs, dir_vecs[..., None])
  File ".local/lib/python3.6/site-packages/torch/functional.py", line 201, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: shape '[1, 1, 2]' is invalid for input of size 0

-----------------------------------------------------------------------

Can you kindly advise how to fix it?

Also, here are three more questions:

- Is there a way to know which picture may or may not contain lines? 
- Does it mean that it won't have junction points either? as lines are formed by junction points. 
- How can we single them out from the exported "h5" file after step#2? 

Thanks so much and have a good day!

**Comment by rpautrat** [comment] 2021-08-19 14:42
Hi,

I am glad to see that it fixed the first error at least! I overlooked a possibility in my previous fix: when only one junction is detected, there are also no line at all that can be detected. Maybe that is the reason for the remaining issue. I just pushed a new fix. Try it and let me know if it was indeed the problem for your test set.

Regarding your additional questions:
- The output of the line detection algorithm is the list of n junctions and a 'line_map', which is a nxn matrix with a 1 in cell (i, j) when junctions i and j are connected by a line. Thus it is fairly easy to know when there are no lines: it is when the line_map is full of zeros.
- You can have junctions but no lines. They will just not be connected to any line. However if there are no junctions detected, then there are of course no lines.
- I think the easiest would be to print which image does not contain any line at the end of Step 3, and then manually suppress the corresponding image and ground truth labels from your dataset. Or just ignore them in the dataloader.

**Comment by miaoqiz** [comment] 2021-08-19 19:43
Hi @rpautrat ,

Thanks so much for the help! I appreciate it.

Now both conversions go through. :)

To print out the index of dataset that lacks either "lines" or "junction points", I updated the code ( from #118 in "convert_homography_results.py" )

------------------------------------------------------------------------------------------

 line_map_pred, junctions_pred, heatmap_pred = line_detector.detect(
                junctions_pred_raw, heatmap_pred, device=device)
            if isinstance(line_map_pred, torch.Tensor):
                line_map_pred = line_map_pred.cpu().numpy()
                if np.all( ( line_map_pred == 0 ) ):
                    print ( "No Line Detected: ", idx, output_key )
            if isinstance(junctions_pred, torch.Tensor):
                junctions_pred = junctions_pred.cpu().numpy()
                if ( junctions_pred.shape[0] < 2 ):
                    print ( "Under 2 Junction Points Found: ", idx, output_key, junctions_pred.shape[0] )
            if isinstance(heatmap_pred, torch.Tensor):
                heatmap_pred = heatmap_pred.cpu().numpy()

------------------------------------------------------------------------------------------

Here is the output:

------------------------------------------------------------------------------------------

19%|########                                   | 15/80 [00:42<01:38,  1.51s/it]No Line Detected:  15 015
 30%|############9                              | 24/80 [00:47<00:57,  1.03s/it]No Line Detected:  24 024
 31%|#############4                             | 25/80 [00:48<01:03,  1.16s/it]No Line Detected:  25 025
Under 2 Junction Points Found:  25 025 0
 44%|##################8                        | 35/80 [01:12<01:30,  2.00s/it]No Line Detected:  35 035
 55%|#######################6                   | 44/80 [01:28<01:18,  2.19s/it]No Line Detected:  44 044
Under 2 Junction Points Found:  44 044 1
 56%|########################1                  | 45/80 [01:29<01:08,  1.95s/it]No Line Detected:  45 045
Under 2 Junction Points Found:  45 045 1
 57%|########################7                  | 46/80 [01:31<01:04,  1.89s/it]No Line Detected:  46 046
Under 2 Junction Points Found:  46 046 0
 59%|#########################2                 | 47/80 [01:33<01:04,  1.95s/it]No Line Detected:  47 047
Under 2 Junction Points Found:  47 047 0
 60%|#########################8                 | 48/80 [01:35<01:03,  1.99s/it]No Line Detected:  48 048
Under 2 Junction Points Found:  48 048 0
 92%|#######################################7   | 74/80 [02:20<00:16,  2.67s/it]No Line Detected:  74 074
 94%|########################################3  | 75/80 [02:21<00:11,  2.34s/it]No Line Detected:  75 075
100%|###########################################| 80/80 [02:34<00:00,  1.93s/it]

------------------------------------------------------------------------------------------

Now the question is - how can I trace back to the original images based on the index? Are the data stored in the "h5" file in the original order?

or can I manually put some code in the dataloader function to skip these indexes in the next two steps? 

Thanks so much and have a good day!

Mio

**Comment by rpautrat** [comment] 2021-08-19 20:48
Perfect, that seems to be a good way to proceed!

Yes, the index will start from 0 to the total number of images in the dataset, and the images will be sorted in lexicographical order. So the image whose name is the smallest in lexicographical order will get key 0, then key 1, etc.

That way you can know what was the original image. Alternatively, you can create a list of keys to ignore, and when the get_item fetches one of these keys, you skip it, or return another image instead.

**Comment by miaoqiz** [comment] 2021-08-20 00:39
Hi @rpautrat ,

Thanks again for the timely reply! I appreciate it.

I think I found the line that I can put the empty keys to skip. 

-------------------------------------------------------------------------------
Line#721 of "holicity_dataset.py":

    def get_data_from_key(self, file_key):
-------------------------------------------------------------------------------

Is the "file_key" the same as the "output_key"? 

Thanks so much and have a good weekend!

**Comment by rpautrat** [comment] 2021-08-23 10:49
Hi,

A quick and dirty way would be to return None for these images, and change the network part to return a loss of 0 when a None image is received.

But you can do it more elegantly, by modifying the following line to ignore the right keys:
https://github.com/cvg/SOLD2/blob/492a71d6b9a9d8d14b6d6586627197d5f9a927f0/dataset/wireframe_dataset.py#L157

**Comment by miaoqiz** [comment] 2021-08-24 00:21
Thanks, @rpautrat 

I adopted the second advice.

When it comes to step#4 on "holicity_dataset", the training seem to be OK until the second epoch due to the "float" and "long" tensor matching issue. Here is the error:

------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "experiment.py", line 227, in <module>
    export_dataset_mode=args.export_dataset_mode, device=device)
  File "experiment.py", line 110, in main
    train(args, dataset_cfg, model_cfg, output_path)
  File "experiment.py", line 82, in train
    train_net(args, dataset_cfg, model_cfg, output_path)
  File "./SOLD2/train.py", line 179, in train_net
    epoch=epoch)
  File "./SOLD2/train.py", line 227, in train_single_epoch
    for idx, data in enumerate(train_loader):
  File "/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "./SOLD2/dataset/holicity_dataset.py", line 43, in holicity_collate_fn
    [b[data_key] for b in batch])
  File "/.local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 3 in sequence argument at position #1 'tensors'

------------------------------------------------------------------------------------------------

I then add a type conversion at line#43 in "holicity_dataset.py". 

                [b[data_key].double() for b in batch])

Then it complained:

------------------------------------------------------------------------------------------------

RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

------------------------------------------------------------------------------------------------

Should I get everything in "DoubleTensor" domain?

Thanks!

**Comment by rpautrat** [comment] 2021-08-24 08:10
Hi, try casting to float() instead, all the tensors should normally be in Float, not Double.

**Comment by miaoqiz** [comment] 2021-08-24 19:47
Hi @rpautrat ,

Thanks so much! 

I made the change by adding "float()", there seems to be another need to change line#149 in the "loss.py" to the following:

----------------------------------------------------------------------------------------------

    dust_bin_label = torch.ones(
        [batch_size, 1, map_shape[0],
         map_shape[1]]).to(junc_map.device).to(torch.**float**)

----------------------------------------------------------------------------------------------

Also, I notice that the loss value sometime becomes negative. What does it mean exactly? 

Thanks, and have a good day!

**Comment by rpautrat** [comment] 2021-08-25 14:10
Yes, it is normal if the total loss goes to the negative. This is due to the regularization loss: https://github.com/cvg/SOLD2/blob/492a71d6b9a9d8d14b6d6586627197d5f9a927f0/model/loss.py#L232

**Comment by miaoqiz** [comment] 2021-09-03 01:29
I am at step#5  with custom dataset. When I visualized the matching lines after 60 epochs of training, the points of the lines seem to stay on the edge of the images.  However,  exported junction points after step#2 looks good. 

Any suggestions? 

Thanks so much and have a good weekend!

**Comment by rpautrat** [comment] 2021-09-03 07:33
What do you mean by "visualizing matching lines" exactly? Are you using the trained model to detect and match lines? Does it mean that all the junctions are only detected on the sides of the image? Can you please add some picture to illustrate your issue? Thanks in advance :)

**Comment by miaoqiz** [comment] 2021-09-03 07:50
In the notebooks folder, "match_lines.ipynb" can be used to plot the matching lines. 

It is interesting that from step#2, the exported points are well positioned in the image with the custom dataset; however, when it comes to train the full model (detector + descriptor) on the same custom dataset at step#5, the points are on the edges and the lines are cross the images from the upper edge to bottom edge.

**Comment by rpautrat** [comment] 2021-09-03 08:36
Did you try re-training the detector only (step 4) on your custom dataset? Does it produce the same result?

**Comment by miaoqiz** [comment] 2021-09-03 09:03
I trained the detector in step 4. I will take a look at the result. Thanks!

**Comment by rpautrat** [comment] 2022-03-12 13:40
I am closing this now, feel free to reopen it if you still have issues.

**Closed by rpautrat** 2022-03-12 13:40 UTC
