### ISSUE TITLE
About Migrating Models to a New Dataset

### ISSUE THREAD

**Issue by LikeRain0** [cvg/SOLD2#79] opened 2023-03-22 08:55 UTC
**Hello, I'm sorry to bother you, but I'm very interested in this work, and then I encountered some problems while training the model on my own dataset.
As you said in #57, I follow your steps to train my model. First, I execute steps 2 and 3 to generate the ground truth of my own dataset, and then use the public pre training model 'sold2_wireframe.tar' training my own model.

The command I executed was：
`python -m sold2.experiment --mode train --dataset_config /home/ccy/ccy/SOLD2/sold2/config/Aachen_dataset.yaml --model_config sold2/config/train_full_pipeline.yaml --exp_name sold2_Aachen_view --pretrained_path /home/ccy/ccy/experiments/pretrained_sold2 --checkpoint_name sold2_wireframe.tar `

Steps 2 and 3 can run normally, and the generated ground truth also meet my expectations. I visualized them in notebooks/visualize_exported_dataset.ipynb.

![output](https://user-images.githubusercontent.com/73823697/226849088-7063d839-2212-4a14-9814-3218c7253b40.png)

However, when executing the above command to train my own model on a pre trained model, I encountered the following runtimeWarning and error：

_/home/ccy/anaconda3/lib/python3.9/site-packages/kornia-0.3.0-py3.9.egg/kornia/geometry/camera/pinhole.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/home/ccy/anaconda3/lib/python3.9/site-packages/kornia-0.3.0-py3.9.egg/kornia/geometry/camera/pinhole.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?_
[Info] Training mode
         Output path: /home/ccy/ccy/experiments/sold2_Aachen_view
         Initializing dataset...
[Info] Initializing Aachen dataset...
         Found filename cache Aachen_train_cache.pkl at /home/ccy/ccy/datasets/Aachen
         Load filename cache...
[Info] Successfully initialized dataset
         Name: Aachen
         Mode: train
         Gt: /home/ccy/ccy/datasets/export_datasets/Aachen_train_gt.h5
         Counts: 4328
----------------------------------------
[Info] Initializing Aachen dataset...
         Found filename cache Aachen_test_cache.pkl at /home/ccy/ccy/datasets/Aachen
         Load filename cache...
[Info] Successfully initialized dataset
         Name: Aachen
         Mode: test
         Gt: /home/ccy/ccy/datasets/export_datasets/Aachen_query_gt.h5
         Counts: 947
----------------------------------------
         Successfully intialized dataloaders.

        --------Initializing model----------
         [Debug] Adding w_junc with value 0.000000 to model
         [Debug] Adding w_heatmap with value 0.000000 to model
         [Debug] Adding w_desc with value 0.000000 to model
        Model architecture: simple
        Backbone: lcnn
        Junction decoder: superpoint_decoder
        Heatmap decoder: pixel_shuffle
        -------------------------------------
         Successfully initialized model

================== Training ====================
_/home/ccy/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:4236: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(_
Epoch [0 / 130] Iter [0 / 1082] loss=5.4002 (5.4002), junc_loss=4.0583 (4.0583), heatmap_loss=0.2500 (0.2500), descriptor_loss=1.0920 (1.0920), gpu_mem=9.1630GB
         Junction     precision=0.0030 (0.0030) / recall=0.3332 (0.3332)
         Junction nms precision=0.0022 (0.0022) / recall=0.0011 (0.0011)
         Heatmap      precision=0.0529 (0.0529) / recall=0.0111 (0.0111)
         Descriptors  matching score=0.0827 (0.0827)
_/home/ccy/ccy/SOLD2/sold2/model/metrics.py:330: RuntimeWarning: invalid value encountered in true_divide
  precision_lst.append(tp / (tp + fp))_
Epoch [0 / 130] Iter [100 / 1082] loss=1.7029 (3.5516), junc_loss=0.6214 (2.3399), heatmap_loss=0.1343 (0.1921), descriptor_loss=1.0004 (1.0462), gpu_mem=9.1630GB
         Junction     precision=0.0000 (0.0015) / recall=0.0000 (0.1666)
         Junction nms precision=0.0000 (0.0011) / recall=0.0000 (0.0005)
         Heatmap      precision=0.0000 (0.0264) / recall=0.0000 (0.0056)
         Descriptors  matching score=0.1201 (0.1014)

Why are those warnings appearing? And the precision seems abnormal.
Can you help me check the reason for the problem? 
Thank you very much and look forward to your reply！

**Comment by rpautrat** [comment] 2023-03-26 17:27
Hi, the warning seems to come from kornia, which might not be compatible with Python 3.9. Did you try with a lower version of Python?

**Comment by LikeRain0** [comment] 2023-03-27 03:34
Hello,thank you very much for your reply！
I currently have Kornia 0.3.0 installed, although there will be warnings, it can be trained. 
I executed the following command to train on my own dataset：
`python -m sold2.experiment --mode train --dataset_config /home/ccy/ccy/SOLD2/sold2/config/Aachen_dataset.yaml --model_config sold2/config/train_full_pipeline.yaml --exp_name sold2_Aachen_view --pretrained --pretrained_path /home/ccy/ccy/experiments/pretrained_sold2 --checkpoint_name sold2_wireframe.tar`

This is one of the epoch training results. Why is the total loss negative? The other losses seem normal.

Epoch [129 / 130] Iter [1000 / 1082] loss=-3.5212 (-3.8086), junc_loss=0.2839 (0.2743), heatmap_loss=0.0787 (0.0693), descriptor_loss=0.0657 (0.0568), gpu_mem=9.5463GB
         Junction     precision=0.1105 (0.1098) / recall=0.7257 (0.8013)
         Junction nms precision=0.2067 (0.2377) / recall=0.1209 (0.1526)
         Heatmap      precision=0.6455 (0.6222) / recall=0.1691 (0.2299)
         Descriptors  matching score=0.8438 (0.8368)

In addition, I test the model I trained on the match_lines.ipynb in the notebook provided by you，I only changed：
ckpt_path = '/home/ccy/ccy/experiments/sold2_Aachen_view/checkpoint-epoch001-end.tar'

But the following error was reported：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_3522785/427355697.py in <module>
     86 }
     87 
---> 88 line_matcher = LineMatcher(
     89         config["model_cfg"], ckpt_path, device, config["line_detector_cfg"],
     90         config["line_matcher_cfg"], config["multiscale"])

~/ccy/SOLD2/sold2/model/line_matcher.py in __init__(self, model_cfg, ckpt_path, device, line_detector_cfg, line_matcher_cfg, multiscale, scales)
     30         self.model = get_model(model_cfg, loss_weights)
     31         checkpoint = torch.load(ckpt_path, map_location=self.device)
---> 32         #self.model.load_state_dict(checkpoint["model_state_dict"])
     33         self.model = self.model.to(self.device)
     34         self.model = self.model.eval()

~/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   2039 
   2040         if len(error_msgs) > 0:
-> 2041             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                                self.__class__.__name__, "\n\t".join(error_msgs)))
   2043         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for SOLD2Net:
	Missing key(s) in state_dict: "w_junc", "w_heatmap", "w_desc", "backbone_net.net.conv1.weight", "backbone_net.net.conv1.bias", "backbone_net.net.bn1.weight", "backbone_net.net.bn1.bias", "backbone_net.net.bn1.running_mean", "backbone_net.net.bn1.running_var", "backbone_net.net.layer1.0.bn1.weight", "backbone_net.net.layer1.0.bn1.bias", "backbone_net.net.layer1.0.bn1.running_mean", "backbone_net.net.layer1.0.bn1.running_var", .........................................

I want to know why such a mistake occurred.

I look forward to hearing from you,Wish you a happy life！

**Comment by rpautrat** [comment] 2023-03-27 09:22
Hi, having a negative loss is normal: this is due to the automatic weighting of the losses and its regularization term that can be negative.

Regarding the error with missing keys, it seems that there is a discrepancy between the loaded model and your checkpoint. What do you get if you print the following line in the notebook:
```print(list(torch.load(ckpt_path, map_location='cpu')['model_state_dict'].keys()))```?

**Comment by LikeRain0** [comment] 2023-03-27 10:59
Hello！

When I execute `print(list(torch.load(ckpt_path, map_location='cpu')['model_state_dict'].keys()))`, the output is:


['module.w_junc', 'module.w_heatmap', 'module.w_desc', 'module.backbone_net.net.conv1.weight', 'module.backbone_net.net.conv1.bias', 'module.backbone_net.net.bn1.weight', 'module.backbone_net.net.bn1.bias', 'module.backbone_net.net.bn1.running_mean', 'module.backbone_net.net.bn1.running_var', 'module.backbone_net.net.bn1.num_batches_tracked', 'module.backbone_net.net.layer1.0.bn1.weight', 'module.backbone_net.net.layer1.0.bn1.bias', 'module.backbone_net.net.layer1.0.bn1.running_mean', 'module.backbone_net.net.layer1.0.bn1.running_var', 'module.backbone_net.net.layer1.0.bn1.num_batches_tracked', 'module.backbone_net.net.layer1.0.conv1.weight', 'module.backbone_net.net.layer1.0.conv1.bias', 'module.backbone_net.net.layer1.0.bn2.weight', 'module.backbone_net.net.layer1.0.bn2.bias', 'module.backbone_net.net.layer1.0.bn2.running_mean', 'module.backbone_net.net.layer1.0.bn2.running_var',.................

**Comment by rpautrat** [comment] 2023-03-27 14:14
Ok, the problem is that all the parameters of your re-trained model are starting with 'module.', while the model is not expecting this. This can happen when you do your training on multiple GPUs for example.

I just pushed a fix to that. Can you try again after pulling the latest changes and let me know if it solved your issue?

**Comment by LikeRain0** [comment] 2023-03-28 02:39
OK,I will test the new changes, but I removed “module.” through the following code and it will run normally
```
        new_state_dict = {}
        for k, v in checkpoint['model_state_dict'].items():
            name = k[7:]
            new_state_dict[name] = v
        self.model.load_state_dict(new_state_dict)
```
I will tell you my test results on the changes as soon as possible. Thank you for your reply！

**Comment by LikeRain0** [comment] 2023-03-28 02:52
OK, I tested the changes and found no previous errors, but an error caused by modifying the OrderedDict object while traversing it will be reported. In Python, when iterators such as the for loop are used to traverse a variable sequence, modifications cannot be made to the sequence, otherwise such errors may be caused. 
It is recommended to use a new copy to store the changed sequence. As in my last answer, there was no error reported.

Thank you very much for your reply, which has helped me a lot！Wish you a happy life！



---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_373824/2733856769.py in <module>
     87 }
     88 
---> 89 line_matcher = LineMatcher(
     90         config["model_cfg"], ckpt_path, device, config["line_detector_cfg"],
     91         config["line_matcher_cfg"], config["multiscale"])

~/ccy/SOLD2/sold2/model/line_matcher.py in __init__(self, model_cfg, ckpt_path, device, line_detector_cfg, line_matcher_cfg, multiscale, scales)
     31         self.model = get_model(model_cfg, loss_weights)
     32         checkpoint = torch.load(ckpt_path, map_location=self.device)
---> 33         checkpoint = adapt_checkpoint(checkpoint["model_state_dict"])
     34         self.model.load_state_dict(checkpoint)
     35 

~/ccy/SOLD2/sold2/misc/train_utils.py in adapt_checkpoint(state_dict)
     54 
     55 def adapt_checkpoint(state_dict):
---> 56     for k, v in state_dict.items():
     57         if k.startswith('module.'):
     58             state_dict[k[7:]] = v

RuntimeError: OrderedDict mutated during iteration

**Comment by rpautrat** [comment] 2023-03-28 07:09
Ah yes, correct. I fixed the main branch with your suggestion. Thanks for reporting it, and glad that your issue is solved!

**Closed by rpautrat** 2023-03-28 07:09 UTC
